export interface Vaccine {
  id: string;
  name: string;
  namePt: string;
  nameEn: string;
  description: string;
  descriptionPt: string;
  ageMonths: number;
  ageLabel: string;
  ageLabelPt: string;
  group: string;
  doses: number;
  doseNumber: number;
  dependsOn?: string[];
  sideEffects: string[];
  sideEffectsPt: string[];
  benefits: string[];
  benefitsPt: string[];
}

export const VACCINE_SCHEDULE: Vaccine[] = [
  {
    id: 'bcg',
    name: 'BCG',
    namePt: 'BCG',
    nameEn: 'BCG',
    description: 'Protects against tuberculosis (TB).',
    descriptionPt: 'Protege contra a tuberculose (TB).',
    ageMonths: 0,
    ageLabel: 'At Birth',
    ageLabelPt: 'Ao Nascer',
    group: 'birth',
    doses: 1,
    doseNumber: 1,
    sideEffects: ['Small scar at injection site', 'Mild fever'],
    sideEffectsPt: ['Pequena cicatriz no local da injeção', 'Febre leve'],
    benefits: ['Protection against severe TB', 'Especially important in high-risk areas'],
    benefitsPt: ['Proteção contra TB grave', 'Especialmente importante em áreas de risco'],
  },
  {
    id: 'hepb-1',
    name: 'Hepatitis B – 1st dose',
    namePt: 'Hepatite B – 1ª dose',
    nameEn: 'Hepatitis B – 1st dose',
    description: 'Protects against liver infection caused by Hepatitis B.',
    descriptionPt: 'Protege contra infecção hepática causada pela Hepatite B.',
    ageMonths: 0,
    ageLabel: 'At Birth',
    ageLabelPt: 'Ao Nascer',
    group: 'birth',
    doses: 3,
    doseNumber: 1,
    sideEffects: ['Soreness at injection site', 'Low fever'],
    sideEffectsPt: ['Dor no local da injeção', 'Febre baixa'],
    benefits: ['Prevents liver disease', 'Reduces risk of liver cancer'],
    benefitsPt: ['Previne doença hepática', 'Reduz risco de câncer de fígado'],
  },
  {
    id: 'penta-1',
    name: 'Pentavalent – 1st dose',
    namePt: 'Pentavalente – 1ª dose',
    nameEn: 'Pentavalent – 1st dose',
    description: 'Combined vaccine: Diphtheria, Tetanus, Pertussis, Hepatitis B, Hib.',
    descriptionPt: 'Vacina combinada: Difteria, Tétano, Coqueluche, Hepatite B, Hib.',
    ageMonths: 2,
    ageLabel: '2 months',
    ageLabelPt: '2 meses',
    group: '2m',
    doses: 3,
    doseNumber: 1,
    sideEffects: ['Fever', 'Irritability', 'Swelling at injection site'],
    sideEffectsPt: ['Febre', 'Irritabilidade', 'Inchaço no local da injeção'],
    benefits: ['Protects against 5 serious diseases', 'Reduces number of injections needed'],
    benefitsPt: ['Protege contra 5 doenças graves', 'Reduz número de injeções necessárias'],
  },
  {
    id: 'ipv-1',
    name: 'Polio (IPV) – 1st dose',
    namePt: 'Polio (IPV) – 1ª dose',
    nameEn: 'Polio (IPV) – 1st dose',
    description: 'Inactivated Polio Vaccine.',
    descriptionPt: 'Vacina Inativada contra Poliomielite.',
    ageMonths: 2,
    ageLabel: '2 months',
    ageLabelPt: '2 meses',
    group: '2m',
    doses: 3,
    doseNumber: 1,
    sideEffects: ['Mild pain at injection site', 'Low-grade fever'],
    sideEffectsPt: ['Dor leve no local da injeção', 'Febre baixa'],
    benefits: ['Prevents polio paralysis', 'Safe and effective'],
    benefitsPt: ['Previne paralisia por pólio', 'Segura e eficaz'],
  },
  {
    id: 'rota-1',
    name: 'Rotavirus – 1st dose',
    namePt: 'Rotavírus – 1ª dose',
    nameEn: 'Rotavirus – 1st dose',
    description: 'Protects against severe diarrhea from rotavirus.',
    descriptionPt: 'Protege contra diarreia severa causada pelo rotavírus.',
    ageMonths: 2,
    ageLabel: '2 months',
    ageLabelPt: '2 meses',
    group: '2m',
    doses: 2,
    doseNumber: 1,
    sideEffects: ['Mild diarrhea', 'Irritability'],
    sideEffectsPt: ['Diarreia leve', 'Irritabilidade'],
    benefits: ['Prevents severe dehydration', 'Reduces hospital visits'],
    benefitsPt: ['Previne desidratação severa', 'Reduz visitas ao hospital'],
  },
  {
    id: 'pneumo-1',
    name: 'Pneumococcal – 1st dose',
    namePt: 'Pneumocócica – 1ª dose',
    nameEn: 'Pneumococcal – 1st dose',
    description: 'Protects against pneumonia, meningitis, and bloodstream infections.',
    descriptionPt: 'Protege contra pneumonia, meningite e infecções no sangue.',
    ageMonths: 2,
    ageLabel: '2 months',
    ageLabelPt: '2 meses',
    group: '2m',
    doses: 3,
    doseNumber: 1,
    sideEffects: ['Fever', 'Decreased appetite', 'Sleepiness'],
    sideEffectsPt: ['Febre', 'Apetite reduzido', 'Sonolência'],
    benefits: ['Prevents severe pneumonia', 'Protects against meningitis'],
    benefitsPt: ['Previne pneumonia grave', 'Protege contra meningite'],
  },
  {
    id: 'penta-2',
    name: 'Pentavalent – 2nd dose',
    namePt: 'Pentavalente – 2ª dose',
    nameEn: 'Pentavalent – 2nd dose',
    description: 'Second dose of combined vaccine.',
    descriptionPt: 'Segunda dose da vacina combinada.',
    ageMonths: 4,
    ageLabel: '4 months',
    ageLabelPt: '4 meses',
    group: '4m',
    doses: 3,
    doseNumber: 2,
    dependsOn: ['penta-1'],
    sideEffects: ['Fever', 'Irritability', 'Swelling at injection site'],
    sideEffectsPt: ['Febre', 'Irritabilidade', 'Inchaço no local da injeção'],
    benefits: ['Boosts immunity', 'Completes primary series'],
    benefitsPt: ['Reforça imunidade', 'Completa série primária'],
  },
  {
    id: 'ipv-2',
    name: 'Polio (IPV) – 2nd dose',
    namePt: 'Polio (IPV) – 2ª dose',
    nameEn: 'Polio (IPV) – 2nd dose',
    description: 'Second dose of polio vaccine.',
    descriptionPt: 'Segunda dose da vacina contra poliomielite.',
    ageMonths: 4,
    ageLabel: '4 months',
    ageLabelPt: '4 meses',
    group: '4m',
    doses: 3,
    doseNumber: 2,
    dependsOn: ['ipv-1'],
    sideEffects: ['Mild pain at injection site', 'Low-grade fever'],
    sideEffectsPt: ['Dor leve no local da injeção', 'Febre baixa'],
    benefits: ['Stronger immunity against polio', 'Critical for eradication'],
    benefitsPt: ['Imunidade mais forte contra pólio', 'Crítica para erradicação'],
  },
  {
    id: 'rota-2',
    name: 'Rotavirus – 2nd dose',
    namePt: 'Rotavírus – 2ª dose',
    nameEn: 'Rotavirus – 2nd dose',
    description: 'Second dose of rotavirus vaccine.',
    descriptionPt: 'Segunda dose da vacina contra rotavírus.',
    ageMonths: 4,
    ageLabel: '4 months',
    ageLabelPt: '4 meses',
    group: '4m',
    doses: 2,
    doseNumber: 2,
    dependsOn: ['rota-1'],
    sideEffects: ['Mild diarrhea', 'Irritability'],
    sideEffectsPt: ['Diarreia leve', 'Irritabilidade'],
    benefits: ['Maximum protection against rotavirus', 'Prevents severe illness'],
    benefitsPt: ['Proteção máxima contra rotavírus', 'Previne doença severa'],
  },
  {
    id: 'pneumo-2',
    name: 'Pneumococcal – 2nd dose',
    namePt: 'Pneumocócica – 2ª dose',
    nameEn: 'Pneumococcal – 2nd dose',
    description: 'Second dose of pneumococcal vaccine.',
    descriptionPt: 'Segunda dose da vacina pneumocócica.',
    ageMonths: 4,
    ageLabel: '4 months',
    ageLabelPt: '4 meses',
    group: '4m',
    doses: 3,
    doseNumber: 2,
    dependsOn: ['pneumo-1'],
    sideEffects: ['Fever', 'Decreased appetite', 'Sleepiness'],
    sideEffectsPt: ['Febre', 'Apetite reduzido', 'Sonolência'],
    benefits: ['Enhanced protection', 'Stronger immune response'],
    benefitsPt: ['Proteção aprimorada', 'Resposta imune mais forte'],
  },
  {
    id: 'penta-3',
    name: 'Pentavalent – 3rd dose',
    namePt: 'Pentavalente – 3ª dose',
    nameEn: 'Pentavalent – 3rd dose',
    description: 'Third and final dose of combined vaccine.',
    descriptionPt: 'Terceira e última dose da vacina combinada.',
    ageMonths: 6,
    ageLabel: '6 months',
    ageLabelPt: '6 meses',
    group: '6m',
    doses: 3,
    doseNumber: 3,
    dependsOn: ['penta-2'],
    sideEffects: ['Fever', 'Irritability', 'Swelling at injection site'],
    sideEffectsPt: ['Febre', 'Irritabilidade', 'Inchaço no local da injeção'],
    benefits: ['Full immunity against 5 diseases', 'Long-lasting protection'],
    benefitsPt: ['Imunidade completa contra 5 doenças', 'Proteção duradoura'],
  },
  {
    id: 'ipv-3',
    name: 'Polio (IPV) – 3rd dose',
    namePt: 'Polio (IPV) – 3ª dose',
    nameEn: 'Polio (IPV) – 3rd dose',
    description: 'Third and final dose of polio vaccine.',
    descriptionPt: 'Terceira e última dose da vacina contra poliomielite.',
    ageMonths: 6,
    ageLabel: '6 months',
    ageLabelPt: '6 meses',
    group: '6m',
    doses: 3,
    doseNumber: 3,
    dependsOn: ['ipv-2'],
    sideEffects: ['Mild pain at injection site', 'Low-grade fever'],
    sideEffectsPt: ['Dor leve no local da injeção', 'Febre baixa'],
    benefits: ['Complete protection against polio', 'Essential for global health'],
    benefitsPt: ['Proteção completa contra pólio', 'Essencial para saúde global'],
  },
  {
    id: 'hepb-2',
    name: 'Hepatitis B – 2nd dose',
    namePt: 'Hepatite B – 2ª dose',
    nameEn: 'Hepatitis B – 2nd dose',
    description: 'Second dose of Hepatitis B vaccine.',
    descriptionPt: 'Segunda dose da vacina contra Hepatite B.',
    ageMonths: 2,
    ageLabel: '2 months',
    ageLabelPt: '2 meses',
    group: '2m',
    doses: 3,
    doseNumber: 2,
    dependsOn: ['hepb-1'],
    sideEffects: ['Soreness at injection site', 'Low fever'],
    sideEffectsPt: ['Dor no local da injeção', 'Febre baixa'],
    benefits: ['Strengthens immunity', 'Reduces infection risk'],
    benefitsPt: ['Reforça imunidade', 'Reduz risco de infecção'],
  },
  {
    id: 'hepb-3',
    name: 'Hepatitis B – 3rd dose',
    namePt: 'Hepatite B – 3ª dose',
    nameEn: 'Hepatitis B – 3rd dose',
    description: 'Third and final dose of Hepatitis B vaccine.',
    descriptionPt: 'Terceira e última dose da vacina contra Hepatite B.',
    ageMonths: 6,
    ageLabel: '6 months',
    ageLabelPt: '6 meses',
    group: '6m',
    doses: 3,
    doseNumber: 3,
    dependsOn: ['hepb-2'],
    sideEffects: ['Soreness at injection site', 'Low fever'],
    sideEffectsPt: ['Dor no local da injeção', 'Febre baixa'],
    benefits: ['Complete immunity against Hep B', 'Lifelong protection'],
    benefitsPt: ['Imunidade completa contra Hep B', 'Proteção vitalícia'],
  },
  {
    id: 'meningo-1',
    name: 'Meningococcal – 1st dose',
    namePt: 'Meningocócica – 1ª dose',
    nameEn: 'Meningococcal – 1st dose',
    description: 'Protects against meningococcal disease.',
    descriptionPt: 'Protege contra doença meningocócica.',
    ageMonths: 3,
    ageLabel: '3 months',
    ageLabelPt: '3 meses',
    group: '3m',
    doses: 3,
    doseNumber: 1,
    sideEffects: ['Fever', 'Headache', 'Fatigue'],
    sideEffectsPt: ['Febre', 'Dor de cabeça', 'Fadiga'],
    benefits: ['Prevents meningitis', 'Protects bloodstream'],
    benefitsPt: ['Previne meningite', 'Protege o sangue'],
  },
  {
    id: 'meningo-2',
    name: 'Meningococcal – 2nd dose',
    namePt: 'Meningocócica – 2ª dose',
    nameEn: 'Meningococcal – 2nd dose',
    description: 'Second dose of meningococcal vaccine.',
    descriptionPt: 'Segunda dose da vacina meningocócica.',
    ageMonths: 5,
    ageLabel: '5 months',
    ageLabelPt: '5 meses',
    group: '5m',
    doses: 3,
    doseNumber: 2,
    dependsOn: ['meningo-1'],
    sideEffects: ['Fever', 'Headache', 'Fatigue'],
    sideEffectsPt: ['Febre', 'Dor de cabeça', 'Fadiga'],
    benefits: ['Boosted immunity', 'Extended protection'],
    benefitsPt: ['Imunidade reforçada', 'Proteção estendida'],
  },
  {
    id: 'meningo-3',
    name: 'Meningococcal – 3rd dose',
    namePt: 'Meningocócica – 3ª dose',
    nameEn: 'Meningococcal – 3rd dose',
    description: 'Third dose of meningococcal vaccine.',
    descriptionPt: 'Terceira dose da vacina meningocócica.',
    ageMonths: 12,
    ageLabel: '12 months',
    ageLabelPt: '12 meses',
    group: '12m',
    doses: 3,
    doseNumber: 3,
    dependsOn: ['meningo-2'],
    sideEffects: ['Fever', 'Headache', 'Fatigue'],
    sideEffectsPt: ['Febre', 'Dor de cabeça', 'Fadiga'],
    benefits: ['Full meningococcal protection', 'Critical for toddlers'],
    benefitsPt: ['Proteção meningocócica completa', 'Crítica para crianças pequenas'],
  },
  {
    id: 'yellow-fever',
    name: 'Yellow Fever',
    namePt: 'Febre Amarela',
    nameEn: 'Yellow Fever',
    description: 'Protects against yellow fever virus.',
    descriptionPt: 'Protege contra o vírus da febre amarela.',
    ageMonths: 9,
    ageLabel: '9 months',
    ageLabelPt: '9 meses',
    group: '9m',
    doses: 1,
    doseNumber: 1,
    sideEffects: ['Low fever', 'Headache', 'Muscle pain'],
    sideEffectsPt: ['Febre baixa', 'Dor de cabeça', 'Dor muscular'],
    benefits: ['Prevents yellow fever', 'Essential in endemic regions'],
    benefitsPt: ['Previne febre amarela', 'Essencial em regiões endêmicas'],
  },
  {
    id: 'mmr-1',
    name: 'MMR – 1st dose',
    namePt: 'Tríplice Viral – 1ª dose',
    nameEn: 'MMR – 1st dose',
    description: 'Protects against Measles, Mumps, and Rubella.',
    descriptionPt: 'Protege contra Sarampo, Caxumba e Rubéola.',
    ageMonths: 12,
    ageLabel: '12 months',
    ageLabelPt: '12 meses',
    group: '12m',
    doses: 2,
    doseNumber: 1,
    sideEffects: ['Fever', 'Mild rash', 'Swollen glands'],
    sideEffectsPt: ['Febre', 'Erupção leve', 'Glândulas inchadas'],
    benefits: ['Prevents 3 viral diseases', 'Prevents birth defects from rubella'],
    benefitsPt: ['Previne 3 doenças virais', 'Previne defeitos congênitos por rubéola'],
  },
  {
    id: 'hepa-1',
    name: 'Hepatitis A – 1st dose',
    namePt: 'Hepatite A – 1ª dose',
    nameEn: 'Hepatitis A – 1st dose',
    description: 'Protects against Hepatitis A infection.',
    descriptionPt: 'Protege contra infecção por Hepatite A.',
    ageMonths: 12,
    ageLabel: '12 months',
    ageLabelPt: '12 meses',
    group: '12m',
    doses: 2,
    doseNumber: 1,
    sideEffects: ['Soreness at injection site', 'Headache', 'Loss of appetite'],
    sideEffectsPt: ['Dor no local da injeção', 'Dor de cabeça', 'Perda de apetite'],
    benefits: ['Prevents foodborne illness', 'Protects liver function'],
    benefitsPt: ['Previne doença transmitida por alimentos', 'Protege função hepática'],
  },
  {
    id: 'pneumo-3',
    name: 'Pneumococcal – 3rd dose',
    namePt: 'Pneumocócica – 3ª dose',
    nameEn: 'Pneumococcal – 3rd dose',
    description: 'Booster dose of pneumococcal vaccine.',
    descriptionPt: 'Dose de reforço da vacina pneumocócica.',
    ageMonths: 12,
    ageLabel: '12 months',
    ageLabelPt: '12 meses',
    group: '12m',
    doses: 3,
    doseNumber: 3,
    dependsOn: ['pneumo-2'],
    sideEffects: ['Fever', 'Decreased appetite', 'Sleepiness'],
    sideEffectsPt: ['Febre', 'Apetite reduzido', 'Sonolência'],
    benefits: ['Long-term pneumonia protection', 'Reduced ear infections'],
    benefitsPt: ['Proteção de longo prazo contra pneumonia', 'Reduz infecções de ouvido'],
  },
  {
    id: 'dtp-booster',
    name: 'DTP Booster',
    namePt: 'DTP Reforço',
    nameEn: 'DTP Booster',
    description: 'Booster for Diphtheria, Tetanus, and Pertussis.',
    descriptionPt: 'Reforço para Difteria, Tétano e Coqueluche.',
    ageMonths: 18,
    ageLabel: '18 months',
    ageLabelPt: '18 meses',
    group: '18m',
    doses: 1,
    doseNumber: 1,
    dependsOn: ['penta-3'],
    sideEffects: ['Pain at injection site', 'Fever', 'Fussiness'],
    sideEffectsPt: ['Dor no local da injeção', 'Febre', 'Irritabilidade'],
    benefits: ['Maintains immunity', 'Prevents whooping cough in toddlers'],
    benefitsPt: ['Mantém imunidade', 'Previne coqueluche em crianças pequenas'],
  },
  {
    id: 'mmr-2',
    name: 'MMR – 2nd dose',
    namePt: 'Tríplice Viral – 2ª dose',
    nameEn: 'MMR – 2nd dose',
    description: 'Second dose of MMR vaccine.',
    descriptionPt: 'Segunda dose da vacina tríplice viral.',
    ageMonths: 15,
    ageLabel: '15 months',
    ageLabelPt: '15 meses',
    group: '15m',
    doses: 2,
    doseNumber: 2,
    dependsOn: ['mmr-1'],
    sideEffects: ['Fever', 'Mild rash', 'Swollen glands'],
    sideEffectsPt: ['Febre', 'Erupção leve', 'Glândulas inchadas'],
    benefits: ['95%+ protection against measles', 'Prevents outbreaks'],
    benefitsPt: ['95%+ proteção contra sarampo', 'Previne surtos'],
  },
  {
    id: 'hepa-2',
    name: 'Hepatitis A – 2nd dose',
    namePt: 'Hepatite A – 2ª dose',
    nameEn: 'Hepatitis A – 2nd dose',
    description: 'Second dose of Hepatitis A vaccine.',
    descriptionPt: 'Segunda dose da vacina contra Hepatite A.',
    ageMonths: 18,
    ageLabel: '18 months',
    ageLabelPt: '18 meses',
    group: '18m',
    doses: 2,
    doseNumber: 2,
    dependsOn: ['hepa-1'],
    sideEffects: ['Soreness at injection site', 'Headache', 'Loss of appetite'],
    sideEffectsPt: ['Dor no local da injeção', 'Dor de cabeça', 'Perda de apetite'],
    benefits: ['Long-term Hep A protection', 'Safe for travel'],
    benefitsPt: ['Proteção de longo prazo contra Hep A', 'Segura para viagens'],
  },
  {
    id: 'varicella',
    name: 'Varicella (Chickenpox)',
    namePt: 'Varicela',
    nameEn: 'Varicella (Chickenpox)',
    description: 'Protects against chickenpox.',
    descriptionPt: 'Protege contra catapora.',
    ageMonths: 12,
    ageLabel: '12 months',
    ageLabelPt: '12 meses',
    group: '12m',
    doses: 1,
    doseNumber: 1,
    sideEffects: ['Mild rash', 'Low fever', 'Soreness'],
    sideEffectsPt: ['Erupção leve', 'Febre baixa', 'Dor'],
    benefits: ['Prevents chickenpox', 'Avoids scarring and complications'],
    benefitsPt: ['Previne catapora', 'Evita cicatrizes e complicações'],
  },
];
